# below must much xrd's <group>/<version>
apiVersion: crossplane.io/v1alpha1
kind: SkyClusterInstance
metadata:
  name: my-cluster
  namespace: default
  labels:
    'backstage.io/kubernetes-id': my-cluster

spec:
  compositionSelector:
    matchLabels:
      ibm.sky.io/provider: aws
      ibm.sky.io/environment: dev
      ibm.sky.io/type: text-classifier
      ibm.sky.io/source: huggingface
  parameters:
     nodes:
       count: 1
     accelerators:
       type: V100:4
